"""empty message

Revision ID: 522764b1123a
Revises: 
Create Date: 2017-04-19 12:27:38.379000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522764b1123a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategoriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('uyeler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('adres', sa.String(length=300), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uyeler_email'), 'uyeler', ['email'], unique=True)
    op.create_index(op.f('ix_uyeler_first_name'), 'uyeler', ['first_name'], unique=False)
    op.create_index(op.f('ix_uyeler_last_name'), 'uyeler', ['last_name'], unique=False)
    op.create_index(op.f('ix_uyeler_username'), 'uyeler', ['username'], unique=True)
    op.create_table('kitaplar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('uye_id', sa.Integer(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategoriler.id'], ),
    sa.ForeignKeyConstraint(['uye_id'], ['uyeler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitaplar')
    op.drop_index(op.f('ix_uyeler_username'), table_name='uyeler')
    op.drop_index(op.f('ix_uyeler_last_name'), table_name='uyeler')
    op.drop_index(op.f('ix_uyeler_first_name'), table_name='uyeler')
    op.drop_index(op.f('ix_uyeler_email'), table_name='uyeler')
    op.drop_table('uyeler')
    op.drop_table('kategoriler')
    # ### end Alembic commands ###
